/// Flutter icons Arrow_Forward
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Arrow_Forward
///      fonts:
///       - asset: fonts/Arrow_Forward.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Arrow_Forward {
  Arrow_Forward._();

  static const _kFontFam = 'Arrow_Forward';
  static const _kFontPkg = null;

  static const IconData icon_ionic_md_arrow_round_back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
