/// Flutter icons Filtre
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Filtre
///      fonts:
///       - asset: fonts/Filtre.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Filtre {
  Filtre._();

  static const _kFontFam = 'Filtre';
  static const _kFontPkg = null;

  static const IconData icon_feather_filter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
