/// Flutter icons FlyPlane
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlyPlane
///      fonts:
///       - asset: fonts/FlyPlane.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlyPlane {
  FlyPlane._();

  static const _kFontFam = 'FlyPlane';
  static const _kFontPkg = null;

  static const IconData path_99 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
