/// Flutter icons TakeOff
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TakeOff
///      fonts:
///       - asset: fonts/TakeOff.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TakeOff {
  TakeOff._();

  static const _kFontFam = 'TakeOff';
  static const _kFontPkg = null;

  static const IconData take_off = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
