/// Flutter icons Two_Arrows
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Two_Arrows
///      fonts:
///       - asset: fonts/Two_Arrows.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Two_Arrows {
  Two_Arrows._();

  static const _kFontFam = 'Two_Arrows';
  static const _kFontPkg = null;

  static const IconData group_73 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
